name: Keepalive

on:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        run: echo "Keepalive to prevent GitHub from disabling scheduled workflows after 60 days of inactivity"
